main:
  debug_bijection: false
  compute_metrics: true
  plot: true

model:
  directory: 'path_to/....social_convrnn.SocialConvRNN_'

hardware:
  allow_growth: true
  per_process_gpu_memory_fraction: 0.3

hydra:
  job_logging:
    handlers:
      console:
        level: INFO
      file:
        level: DEBUG
  run:
    dir: 'path_to/esp_infer_results/${now:%Y-%m}/${now:%m-%d-%H-%M-%S}_${dataset.class}

images:
  ext: 'jpg'
  figsize: [16, 16]

split: 'test'

dataset:
  plot_allchannel: false

plotting:
  bev_kwargs:
    onechannel: True
    allchannel: False
    fmt: 'carla'

defaults:
  - dataset: nuscenes_dataset
