main:
  seed: 42
  eager: false
  tag: ""

hydra:
  job_logging:
    root:
       level: INFO
    handlers:
      console:
        level: INFO
      file:
        level: DEBUG
  run:
    dir: 'path_to/esp_train_results/${now:%Y-%m}/${now:%m-%d-%H-%M-%S}_${dataset.params._name}_${bijection.class}_${main.tag}
distribution:
  params:
    K: 12
    sample_K: 12

bijection:
  params:
    A: 1

dataset:
  plot_allchannel: false

defaults:
  - hardware: shared_gpu
  - optimizer: sgd_optimizer
  - dataset: trimodal_dataset
  - bijection: social_convrnn
  - distribution: bijective_distribution
  - objective: forward_kl
  - sample_metric: mhat
  - proxy: empty_proxy
